### PR TITLE
Fixed regex mistake

### PR DESCRIPTION
**Pull request by Mintey**
Fixed regex mistake in hasInvalidCharacters used in validate for commands. Now allows the character . for file-endings

### CODE REVIEW

**Comment by skriez** [comment]
This commit breaks the server.

**Comment by skriez** [comment]
The correct regex should be "[\\^A-Za-z0-9_\\. ]*", and the validation logic is wrong. ProcessCommand uses it to validate expecting false, LoginCommand uses it to validate and expects true. As such, it is inconsistent and should be fixed.

**Comment by 23Skidoo** [comment]
When we fix this, can we add a test so this doesn't happen again?

**Comment by skriez** [comment]
I'd say so

**Pull request merged**
