### PR TITLE
Db test fixes

### PR DESCRIPTION
**Pull request by erisam**
Fixed encoding issue in SearchDatabaseTest (again...)

### CODE REVIEW

**Comment by 23Skidoo** [comment]
> This should not be merged anywhere!!!!

Looks suspicious.

**Comment by erisam** [comment]
I don't know how to remove the specific commit from the pull request. The commit contains a file that is removed in the later commits ("SearchDatabaseTests2.java"). If you can help me remove that commit from the pull request, it would be great. But the erroneous file should not be included even if it's not.

**Comment by currybullen** [comment]
This might have already been taken care of but I think you can do a:

git reset --hard 0c74b8f

followed by:

git push DBTestFixes -f

As you push the pull request should change accordingly.

**Comment by 23Skidoo** [comment]
Cleaned up and rebased against `develop`, see #285. Closing in favour of #285.

**Comment by 23Skidoo** [comment]
> I don't know how to remove the specific commit from the pull request.

In general, you edit history with `rebase -i`. The version of Git on lab machines is somewhat old, however, and I had some strange problems when trying to rebase your branch there.

**Pull request closed without merging**
