### PR TITLE
Make picard callable

### PR DESCRIPTION
**Pull request by knownsoldier**
Implemented method calling picard for removing duplicates in new raw2profile process pipeline. Also merged with develop a couple of times..

### CODE REVIEW

**Comment by 23Skidoo** [comment]
See #256 and #255, we've already added pyicos and picard.

**Comment by knownsoldier** [comment]
Yes, but this includes some code using picard as well, not only the dependencies.

**Comment by 23Skidoo** [comment]
But we don't want to have two copies of `picard` in the repo.

**Comment by 23Skidoo** [comment]
Would be also nice to have tests for this, I guess.

**Comment by knownsoldier** [comment]
Yes of course, there is no support for this anywhere along the pipeline which is the next thing to implement.

**Pull request merged**
