### PR TITLE
Imported Bcrypt

### PR DESCRIPTION
**Pull request by timqy**
Bcrypt imported and implemented into project.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
Something is off, I don't see your commits.

**Comment by tastyburger** [comment]
I presume the requester is trying to merge updates in the main branch into own branch.

**Comment by 23Skidoo** [comment]
Well, you don't need to open a PR for this. Use `git merge`.

**Comment by knownsoldier** [comment]
This pull request seems nonsense. Closing.

**Comment by skriez** [comment]
This pull request seems nonsense. Closing.

**Pull request closed without merging**
