### PR TITLE
Release database file

### PR DESCRIPTION
**Pull request by unicornmaster**
This file setsup the database empty with only three users (jan, per and yuri all with admin rights and the obvius password as default).
Use it by set the vagrant manifest file to load release_database_tuples.sql instead for add_test_tuples.sql and then reboot

Tested on vagrant-1 (seems ok!)

### CODE REVIEW

**Comment by tastyburger** [comment]
Did you ask them before uploading their information on the internet?

**Comment by 23Skidoo** [comment]
It's publicly available anyway, see http://www.umu.se/sok/english/staff-directory/?uid=yusc0002&guise=base

**Comment by tastyburger** [comment]
Well yeah, it's still something they have control over. If they ever get spammed because their emails are on github, we are the blame. Real data should never be shared through git.

**Comment by 23Skidoo** [comment]
Well, we can do a `rebase` and `push -f` if push comes to shove.

**Pull request merged**
