### PR TITLE
Dlagring0421 - Support for login based on User_Info table

### PR DESCRIPTION
**Pull request by yakrar**
Mostly the same as the equivalent pr yesterday. I've also added a testuser entry to `add_test_tuples.sql` called "testuser". This script should obviously not be used in live deployment.

In case it wasn't obvious: yes, this replaces the old "login" mechanism. This merge would make it impossible to login without a valid user in the `User_Info` table.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
One other possible improvement is to use [bcrypt](http://codahale.com/how-to-safely-store-a-password/) instead of SHA 256.

**Comment by 23Skidoo** [comment]
See also http://chargen.matasano.com/chargen/2015/3/26/enough-with-the-salts-updates-on-secure-password-schemes.html.

**Comment by yakrar** [comment]
True; although I figure that could equally well be implemented in a later feature branch. The main point of this pr was to get the logic working. 

And anyhoo, this is far better than the "hash in a textfile" we've been using so far.

**Comment by 23Skidoo** [comment]
Yep, these links are just FYI.

**Comment by yakrar** [comment]
Got an RL ok from skriez. Merging this now.

**Pull request merged**
