### PR TITLE
Added support for storing salt + hash instead of psswd in database

### PR DESCRIPTION
**Pull request by yakrar**
I'd like for someone from BL/Server to have a look at this, since some changes concern (and were commited by) them.

### CODE REVIEW

**Comment by yakrar** [comment]
We seem to be failing conversion tests. Will look in to this later (busy due to a lecture right now).

**Comment by knownsoldier** [comment]
The failing of conversion tests is due to some hardcoded paths used in test methods. They need to be incorperated in the project, perhaps under a directory for test data?

**Comment by 23Skidoo** [comment]
I've disabled failing tests.

**Comment by yakrar** [comment]
Closing this without merging anyway; It needs some fixing.

**Pull request closed without merging**
